### ISSUE TITLE
Patch goal skips multi-release jar files for automatic modules

### ISSUE THREAD

**Issue by vitalh** [ghackenberg/jigsaw-maven-plugin#2]
Jar files can be multi-release but without `module-info.class`, such jars are skipped what is wrong.

Jar example: https://mvnrepository.com/artifact/org.jboss.threads/jboss-threads
Code: https://github.com/ghackenberg/jigsaw-maven-plugin/blob/main/src/main/java/io/github/ghackenberg/maven/plugins/jigsaw/PatchMojo.java#L79

**Comment by vitalh** [comment]
Yes, this solution works to me. But the code could be improved.

**Comment by ghackenberg** [comment]
Perfect, then I will close this issue. For code cleanup I have created a separate issue. Thanks @vitalh!
