### ISSUE TITLE
Do "cleanup message"

### ISSUE THREAD

**Issue by ghackenberg** [ghackenberg/jigsaw-maven-plugin#7]
Do "cleanup message"

**Comment by ghackenberg** [comment]
@vitalh could you explain what you meant with "cleanup message"? Thanks!

**Comment by vitalh** [comment]
I mean "Jdeps did not terminate successfully!" shouldn't be ended with "successfully!". It's hard to understand is fail or not. Better don't use negation in error message.

**Comment by ghackenberg** [comment]
I see. I will change that!

**Comment by ghackenberg** [comment]
In release `v1.1.2` I reworked the logging functionality. Hope it is much better now!
